language: cpp

os:
  - linux

env:
  - LIBAV=libav-stable
  - LIBAV=libav-git
  - LIBAV=ffmpeg-stable
  - LIBAV=ffmpeg-git

compiler:
  - clang

branches:
  only:
    - master
    - release

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-default libqt5gui5 libqt5core5 libqt5declarative5 libqt5x11extras5

before_install: ./travis-deps libass-stable $LIBAV libmpv-git
script:
  - ./make.sh

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#baka-mplayer-dev"
    on_success: change
    on_failure: always

