language: cpp

os:
  - linux

env:
#  - LIBAV=libav-stable
  - LIBAV=libav-git
#  - LIBAV=ffmpeg-stable
#  - LIBAV=ffmpeg-git

compiler:
  - clang

branches:
  only:
    - master
    - release

install:
  - echo "deb http://ftp.debian.org sid main" | sudo tee --append /etc/apt/sources.list
  - echo "deb-src http://ftp.debian.org sid main" | sudo tee --append /etc/apt/sources.list

before_install: TRAVIS_OS_NAME=linux; ./travis-deps libass-stable $LIBAV libmpv-git
script:
  - ./make.sh

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#baka-mplayer-dev"
    on_success: change
    on_failure: always

