language: cpp

os:
  - linux

env:
#  - LIBAV=libav-stable
  - LIBAV=libav-git
#  - LIBAV=ffmpeg-stable
#  - LIBAV=ffmpeg-git

compiler:
  - clang

branches:
  only:
    - master
    - release

install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa

before_install: TRAVIS_OS_NAME=linux; ./travis-deps libass-stable $LIBAV libmpv-git
script:
  - ./make.sh

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#baka-mplayer-dev"
    on_success: change
    on_failure: always

