language: cpp

sudo: true

os:
  - linux

env:
  - QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake

compiler:
  - gcc

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - git
    - gcc
    - g++
    - autoconf
    - automake
    - libtool
    - yasm
    - devscripts
    - libfreetype6-dev
    - libfribidi-dev
    - libfontconfig1-dev
    - pkg-config
    - qtbase5-dev
    - qt5-qmake
    - qttools5-dev-tools
    - qtdeclarative5-dev
    - libqt5svg5-dev
    - libqt5network5
    - libqt5x11extras5-dev
    - libmpv-dev

cache:
  directories:
  - build

before_install:
  - sudo apt-get purge --auto-remove libc-bin

script:
  - bash configure
  - make -j $(grep -c ^processor /proc/cpuinfo)

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#baka-mplayer"
    on_success: change
    on_failure: always
