language: cpp

os:
  - linux

env:
#  - LIBAV=libav-stable
  - LIBAV=libav-git
#  - LIBAV=ffmpeg-stable
#  - LIBAV=ffmpeg-git

compiler:
  - clang

branches:
  only:
    - master
    - release

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo add-apt-repository --yes 'deb http://http.debian.net/debian wheezy-backports main'
  - sudo apt-get update
  - sudo apt-get -t wheezy-backports install "libqt5x11extras5-dev"
  - sudo apt-get install pkg-config fontconfig libfribidi-dev yasm qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libqt5svg5-dev libsqlite3-dev cmake ninja-build
  - TRAVIS_OS_NAME=linux; ./travis-deps libass-stable $LIBAV libmpv-git

script:
  - ./make.sh

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#baka-mplayer-dev"
    on_success: change
    on_failure: always

