language: cpp

os:
  - linux

compiler:
  - clang

branches:
  only:
    - master
    - release

install:
  - sudo apt-get update
  - sudo apt-get install libqt5-dev

script:
  - ./make.sh

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#baka-mplayer-dev"
    on_success: change
    on_failure: always

