language: cpp

os:
  - linux

compiler:
  - clang

branches:
  only:
    - master
    - release

script:
  - ./make.sh

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#baka-mplayer-dev"
    on_success: change
    on_failure: always

